#!/bin/sh

build() {
    local v="gitconfig"
    build_file $v
    build_file gitignore
    project_enabled "ctags"
    local i=$?
    delete_chunk "ctags" "${BUILD_PATH}/${v}" $i
    if [ ${i} -eq 0 ]; then
        build_submodule ctag-hooks
    fi
}

$@
