#! /usr/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        3
bspc config window_gap          16
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Borders
bspc config normal_border_color "#504339"
bspc config active_border_color "#504339"
bspc config focused_border_color "#0084a5"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#960000"

bspc config top_padding 16

# TODO general path
/home/buster/bin/panel &

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a feh floating=on manage=off
