#! /usr/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          0
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Borders
bspc config normal_border_color "#000000"
bspc config active_border_color "#000000"
bspc config focused_border_color "#FFFFFF"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#960000"

bspc config top_padding 16

# TODO general path
/home/buster/scripts/panel &

bspc rule -a feh floating=on manage=off
