#! /usr/bin/sh


BORDER_SIZE=1

bspc config border_width $BORDER_SIZE
bspc config window_gap -$BORDER_SIZE

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Borders
bspc config normal_border_color "#110807"
bspc config active_border_color "#110807"
bspc config focused_border_color "#FFFFFF"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#960000"

for side in right bottom left; do
  bspc config ${side}_padding $BORDER_SIZE
done
bspc config top_padding 17

# TODO general path
/home/buster/scripts/panel &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
