#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT
export PATH=$PATH:$HOME/scripts
export PANEL_FIFO="/tmp/panel-fifo"
export PANEL_HEIGHT=18
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &

while true; do echo ABattery: $(acpi | grep -o "[0-9]*%") > "$PANEL_FIFO" && sleep 5; done &
while true; do date "+D%d %B %H:%M" > "$PANEL_FIFO" && sleep 1; done &

. /home/buster/scripts/panel_colors
FONT_FAMILY='Inconsolata'
FONT_SIZE=14
cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &

wait
